### ISSUE TITLE
Background/Hero does not work

### ISSUE THREAD

**Issue by Sugoyh** [mmatyas/pegasus-theme-flixnet#5]
I am trying to set a background/hero, but it is not displaying. In `metadata.pegasus.txt` I've tried several options:
```
assets.background: {.png file}

background: {.png file}

assets:
  background: {.png file}
  …

assets:
  assets.background: {.png file}
  …
```
Note: while default theme, `assets.background: {.png file}` works (see 2nd image).

![pegasus-fe_oHAZlMfdWj](https://github.com/user-attachments/assets/f762fa7e-8b8c-4b68-9fe7-805016538e6c)
![pegasus-fe_2CnNXI7BqM](https://github.com/user-attachments/assets/56295bc4-10c1-4431-964c-bcd3336165b6)
